version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/geogopher
hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh
    - location: scripts/delete_old_files.sh
      runas: root
  AfterInstall:
    - location: scripts/change_permissions.sh
    - location: scripts/set_symlinks.sh
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 60
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 60
      runas: root
